local SRW_Lord_Group = {
  --vcounts
    ["pro02_vmp_isabella_von_carstein"] = "Isabella",
    ["wh2_dlc11_vmp_bloodline_von_carstein"] = "Carstain",
    ["wh2_dlc11_vmp_bloodline_blood_dragon"] = "Blood_Dragon",
    ["wh_dlc05_vmp_red_duke"] = "Blood_Dragon",
    ["wh2_dlc11_vmp_bloodline_strigoi"] = "Strigoi",
    ["dlc04_vmp_helman_ghorst"] = "Ghorst",
    ["vmp_bloodline_fallen_knight"] = "Mixu_Knight",
  --elves
    ["wh2_main_hef_tyrion"] = "Tyrion",
    ["wh2_dlc15_hef_archmage_beasts"] = "Tyrion",
    ["wh2_dlc15_hef_archmage_death"] = "Tyrion",
    ["wh2_dlc15_hef_archmage_fire"] = "Tyrion",
    ["wh2_dlc15_hef_archmage_heavens"] = "Tyrion",
    ["wh2_dlc15_hef_archmage_high"] = "Tyrion",
    ["wh2_dlc15_hef_archmage_life"] = "Tyrion",
    ["wh2_dlc15_hef_archmage_light"] = "Tyrion",
    ["wh2_dlc15_hef_archmage_metal"] = "Tyrion",
    ["wh2_dlc15_hef_archmage_shadows"] = "Tyrion",
    ["wh2_main_hef_prince"] = "Tyrion",
    ["wh2_main_hef_princess"] = "Tyrion",
    ["wh2_dlc10_hef_alarielle"] = "Alarielle",
    ["wh2_main_def_morathi"] = "Morathi",
    ["wh2_dlc14_def_high_beastmaster"] = "BeastMaster",
    ["wh2_main_lzd_saurus_old_blood"] = "Zaurus",
    ["wh2_main_lzd_kroq_gar"] = "Zaurus",
    ["wh2_dlc13_lzd_gor_rok"] = "Zaurus",
  --liz and skav
    ["wh2_dlc12_lzd_red_crested_skink_chief"] = "Skink",
    ["wh2_dlc12_lzd_red_crested_skink_chief_legendary"] = "Skink",
    ["wh2_dlc13_lzd_red_crested_skink_chief_horde"] = "Skink",
    ["wh2_dlc13_lzd_kroxigor_ancient"] = "Kroxi",
    ["wh2_dlc13_lzd_kroxigor_ancient_horde"] = "Kroxi",
    ["wh2_dlc12_lzd_tehenhauin"] = "Tehen",
    ["wh2_dlc09_skv_tretch_craventail"] = "Tretch",
    ["wh2_dlc12_skv_ikit_claw"] = "Ikit",
    ["wh2_dlc12_skv_warlock_master"] = "Warlock",
    ["Thom_vulkan_moltskin_searflesh"] = "Vulcan",
    ["thom_iron_mask"] = "Ferric",
  --vcoast
    ["wh2_dlc14_skv_master_assassin"] = "Assassin",
    ["wh2_dlc11_cst_admiral_fem"] = "Pirate",
    ["wh2_dlc11_cst_admiral_fem_death"] = "Pirate",
    ["wh2_dlc11_cst_admiral_fem_deep"] = "Pirate",
    ["wh2_dlc11_cst_admiral_tech_04"] = "Pirate",
    ["wh2_dlc11_cst_harkon"] = "Harkon",
    ["wh2_dlc11_cst_admiral"] = "Pirate",
    ["wh2_dlc11_cst_admiral_death"] = "Pirate",
    ["wh2_dlc11_cst_admiral_deep"] = "Pirate",
    ["wh2_dlc11_cst_admiral_tech_01"] = "Pirate",
    ["wh2_dlc11_cst_admiral_tech_02"] = "Pirate",
    ["wh2_dlc11_cst_admiral_tech_03"] = "Pirate",
    ["wh2_dlc11_cst_noctilus"] = "Noctil",
    ["wh2_dlc11_cst_aranessa"] = "Aranessa",
  --Old world
    ["wh2_dlc13_emp_cha_huntsmarshal_0"] = "Hunter",
    ["emp_balthasar_gelt"] = "Gelt",
    ["grn_goblin_great_shaman"] = "Goblin",
    ["dlc06_grn_night_goblin_warboss"] = "Goblin",
    ["dlc06_grn_skarsnik"] = "Goblin",
    ["dlc06_grn_wurrzag_da_great_prophet"] = "Wurzag",
    ["grn_azhag_the_slaughterer"] = "Azhag",
    ["wh_dlc08_nor_wulfrik"] = "Wulfrik",
    ["wh_dlc08_nor_throgg"] = "Throgg",
    ["ws_grn_tinitt_foureyes"] = "Forest",
    ["ws_grn_grak_beastbasha"] = "BeastBasha",
  --TEB
    --["teb_tilea"] = "Tileaman",
    --["teb_borgio_the_besieger"] = "Besieger",
  --Kislev
    ["wh2_deco_boris"] = "Boris",
    ["mixu_katarin_the_ice_queen"] = "Katya",
  --Lost factions
    ["aky_chief_fimir_great_weapons"] = "Fimir",
    ["elo_chief_ugma"] = "Trololo",
    
  
  }
  
  